<?php
$carros = array(
    new carro("2019", "Fiat", "Cronos", "Vermelho", "Automático"),
    new carro("2013", "Honda", "Civic", "Preto", "Manual"),
    new carro("2006", "Ford", "Focus", "Marrom", "Manual"),
    new carro("2016", "Chevrolet", "Onix", "Azul", "Manual"),
    new carro("2020", "Hyundai", "HB20", "Branco", "Manual"),
    new carro ("2001", "BMW", "X5", "Preto", "Automático"),
    new carro ("2007", "Nissan", "March", "Prata", "Automático"),
    new Carro("2023", "Kia", "Sportage", "Verde", "Automático"),
    new Carro("2021", "Fiat", "Uno", "Azul", "Manual"),
    new Carro(2022, "Renault", "Kwid", "Branco", "Manual"),
    new Carro(2023, "Peugeot", "208", "Prata", "Automático"),
    new Carro(2021, "Citroën", "C4 Cactus", "Vermelho", "Automático"),
    new Carro(2022, "Jeep", "Renegade", "Preto", "Automático"),
    new Carro(2023, "Land Rover", "Range Rover Evoque", "Branco", "Automático"),
    new Carro(2022, "Volvo", "XC60", "Cinza", "Automático"),
    new Carro(2021, "Subaru", "Forester", "Azul", "Automático"),
    new Carro(2023, "Mazda", "CX-5", "Prata", "Automático"),
    new Carro(2022, "Lexus", "RX", "Preto", "Automático"),
    new Carro(2021, "Infiniti", "QX50", "Branco", "Automático"),
    new Carro(2023, "Acura", "MDX", "Cinza", "Automático"),
    new Carro(2022, "Porsche", "Cayenne", "Vermelho", "Automático"),
    new Carro(2021, "Jaguar", "F-Pace", "Azul", "Automático"),
    new Carro(2023, "Tesla", "Model S", "Branco", "Elétrico"),
    new Carro(2022, "Rivian", "R1T", "Verde", "Elétrico"),
    new Carro(2021, "Lucid", "Air", "Prata", "Elétrico"),
    new Carro(2023, "Polestar", "2", "Azul", "Elétrico"),
    new Carro(2022, "Byton", "M-Byte", "Preto", "Elétrico"),
    new Carro(2021, "NIO", "ES8", "Vermelho", "Elétrico"),
    new Carro(2023, "Rivian", "R1S", "Cinza", "Elétrico"),
    new Carro(2022, "Faraday Future", "FF 91", "Branco", "Elétrico"),
    new Carro(2021, "Canoo", "MPDV", "Amarelo", "Elétrico"),
    new Carro(2023, "Bollinger", "B2", "Laranja", "Elétrico"),
    new Carro(2022, "Lordstown", "Endurance", "Prata", "Elétrico"),
    new Carro(2021, "Nikola", "Badger", "Azul", "Elétrico")
);